# Path to your oh-my-zsh configuration.
ZSH=$HOME/.oh-my-zsh

# Set name of the theme to load.
# Look in ~/.oh-my-zsh/themes/
# Optionally, if you set this to "random", it'll load a random theme each
# time that oh-my-zsh is loaded.
#ZSH_THEME="robbyrussell"
ZSH_THEME="alanpeabody"

# Example aliases
# alias zshconfig="mate ~/.zshrc"
# alias ohmyzsh="mate ~/.oh-my-zsh"

# Set to this to use case-sensitive completion
# CASE_SENSITIVE="true"

# Comment this out to disable bi-weekly auto-update checks
# DISABLE_AUTO_UPDATE="true"

# Uncomment to change how often before auto-updates occur? (in days)
# export UPDATE_ZSH_DAYS=13

# Uncomment following line if you want to disable colors in ls
# DISABLE_LS_COLORS="true"

# Uncomment following line if you want to disable autosetting terminal title.
# DISABLE_AUTO_TITLE="true"

# Uncomment following line if you want to disable command autocorrection
# DISABLE_CORRECTION="true"

# Uncomment following line if you want red dots to be displayed while waiting for completion
# COMPLETION_WAITING_DOTS="true"

# Uncomment following line if you want to disable marking untracked files under
# VCS as dirty. This makes repository status check for large repositories much,
# much faster.
# DISABLE_UNTRACKED_FILES_DIRTY="true"

# Which plugins would you like to load? (plugins can be found in ~/.oh-my-zsh/plugins/*)
# Custom plugins may be added to ~/.oh-my-zsh/custom/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)
plugins=(git)

source $ZSH/oh-my-zsh.sh

# Customize to your needs...

export AWS_ACCESS_KEY=AKIAJUQBGX5Y7HGQHLHQ
export AWS_SECRET_KEY=+jffJ1xIV+uBO8lKyEWOGdQFZJ7v8KKdvTdc3vtg

export AWS_AUTO_SCALING_HOME=/home/michael/Soft/aws/AutoScaling-1.0.61.2
export AWS_CREDENTIAL_FILE=/home/michael/Soft/aws/credential-new.txt
export EC2_HOME=/home/michael/Soft/aws/ec2-api-tools-1.6.9.0
export AWS_CLOUDWATCH_HOME=/home/michael/Soft/aws/CloudWatch-1.0.13.4

export JAVA_HOME=/opt/jdk1.7.0_25
export CLASS_PATH=/opt/jdk1.7.0_25/lib
export PATH=$PATH:/opt/jdk1.7.0_25/bin

# golang for linux
export GOROOT=~/soft/go
export GOARCH=amd64
export GOOS=darwin
export GOTOOLS=$GOROOT/pkg/tool/
export GOPATH=~/workspace/mygo:~/workspace/mygo/src/github.com/newthinker/aws-api
export PATH=$PATH:$GOROOT/bin:$GOROOT/pkg/tool/darwin_amd64:~/workspace/mygo/bin

# golang for mac os
export GOROOT=~/Soft/go
export GOARCH=amd64
export GOOS=linux
export GOBIN=$GOROOT/bin/
export GOTOOLS=$GOROOT/pkg/tool/
export GOPATH=~/workspace/go:~/workspace/go/src/github.com/newthinker/aws-api
export PATH=$PATH:$GOBIN:$GOTOOLS:$GOROOT/pkg/tool/linux_amd64

# python path
export PYTHONPATH=$PYTHONPATH:~/workspace/madeira/source/api/Source

# java
export JAVA_HOME=/usr/local/java/jdk1.7.0_60
export PATH=$PATH:$JAVA_HOME/bin
