# Path to your oh-my-zsh configuration.
ZSH=$HOME/.oh-my-zsh

# Set name of the theme to load.
# Look in ~/.oh-my-zsh/themes/
# Optionally, if you set this to "random", it'll load a random theme each
# time that oh-my-zsh is loaded.
ZSH_THEME="robbyrussell"
#ZSH_THEME="alanpeabody"

# Example aliases
# alias zshconfig="mate ~/.zshrc"
# alias ohmyzsh="mate ~/.oh-my-zsh"

# Set to this to use case-sensitive completion
# CASE_SENSITIVE="true"

# Comment this out to disable bi-weekly auto-update checks
# DISABLE_AUTO_UPDATE="true"

# Uncomment to change how often before auto-updates occur? (in days)
# export UPDATE_ZSH_DAYS=13

# Uncomment following line if you want to disable colors in ls
# DISABLE_LS_COLORS="true"

# Uncomment following line if you want to disable autosetting terminal title.
# DISABLE_AUTO_TITLE="true"

# Uncomment following line if you want to disable command autocorrection
# DISABLE_CORRECTION="true"

# Uncomment following line if you want red dots to be displayed while waiting for completion
# COMPLETION_WAITING_DOTS="true"

# Uncomment following line if you want to disable marking untracked files under
# VCS as dirty. This makes repository status check for large repositories much,
# much faster.
# DISABLE_UNTRACKED_FILES_DIRTY="true"

# Which plugins would you like to load? (plugins can be found in ~/.oh-my-zsh/plugins/*)
# Custom plugins may be added to ~/.oh-my-zsh/custom/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)
plugins=(git bundler osx autojumps mvn)

source $ZSH/oh-my-zsh.sh

# Customize to your needs...

# alias
alias cls='clear'
alias ll='ls -l'
alias la='ls -a'
alias vi='vim'
alias grep="grep --color=auto"
alias -s gz='tar -xzvf'
alias -s tgz='tar -xzvf'
alias -s zip='unzip'
alias -s bz2='tar -xjvf'

# autojumps
[[ -s ~/.autojump/etc/profile.d/autojump.sh ]] && . ~/.autojump/etc/profile.d/autojump.sh

export AWS_AUTO_SCALING_HOME=/home/michael/Soft/aws/AutoScaling-1.0.61.2
#export AWS_CREDENTIAL_FILE=/home/michael/Soft/aws/credential-new.txt
export EC2_HOME=/home/michael/Soft/aws/ec2-api-tools-1.6.9.0
export AWS_CLOUDWATCH_HOME=/home/michael/Soft/aws/CloudWatch-1.0.13.4

unamestr=`uname`
if [[ "$unamestr" == 'Linux' ]]; then
    # golang for linux
    export GOROOT=/usr/local/go
    export GOARCH=amd64
    export GOOS=linux
    export GOBIN=$GOROOT/bin/
    export GOTOOLS=$GOROOT/pkg/tool/
    export GOPATH=~/workspace/go
    export PATH=$PATH:$GOBIN:$GOTOOLS:$GOROOT/pkg/tool/linux_amd64

    # virtualenvwrapper setting
    export WORKON_HOME=/mc/virtualenv
    source /usr/bin/virtualenvwrapper.sh

elif [[ "$unamestr" == 'Darwin' ]]; then
    # golang for mac os
    export GOROOT=/usr/local/go
    export GOARCH=amd64
    export GOOS=darwin
    export GOTOOLS=$GOROOT/pkg/tool/
    export GOPATH=~/workspace/go
    export PATH=$PATH:$GOROOT/bin:$GOROOT/pkg/tool/darwin_amd64:~/workspace/go/bin

    # java
    export JAVA_6_HOME=/System/Library/Java/JavaVirtualMachines/1.6.0.jdk/Contents/Home
    export JAVA_8_HOME=/Library/Java/JavaVirtualMachines/jdk1.8.0_51.jdk/Contents/Home
    export JAVA_HOME=$JAVA_8_HOME
    export JRE_HOME=$JAVA_8_HOME/jre
    export CLASSPATH=.:$JRE_HOME/lib/rt.jar

    # virtualenvwrapper settings
    WORKON_HOME=/Users/zuowei/workspace/virtualenv
    source /usr/local/bin/virtualenvwrapper.sh
fi

# python path
export PYTHONPATH=$PYTHONPATH:~/workspace/madeira/source/api/Source:~/workspace/madeira/source/cloudfielder-api/Source:~/workspace/oneapm/OneRASP-api/Source
